# Generated by Django 4.2 on 2024-02-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_lessons_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='courses',
            new_name='course',
        ),
    ]
