# Generated by Django 4.2 on 2024-02-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_lessons_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['title'], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
    ]
