# Generated by Django 4.2 on 2024-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_lessons_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
