# Generated by Django 4.2 on 2024-02-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_lessons_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['title'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.PositiveIntegerField(default=150000, verbose_name='стоимость'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='price',
            field=models.PositiveIntegerField(default=10000, verbose_name='стоимость'),
        ),
    ]
